# Generated by Django 2.2.3 on 2019-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Link', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Blogger_Name', models.CharField(max_length=10)),
                ('Blogger_Link', models.CharField(max_length=30)),
                ('Post_Date', models.DateField()),
                ('Post_Contents', models.TextField()),
            ],
        ),
    ]
